### ISSUE TITLE
Publish on netlify instead of github gh-pages branch

### ISSUE THREAD

**Issue by jldec** [projectriff/projectriff.io#141]
Publishing on netlify will enable automatic publishing whenever we push to master.
It will also give us better support for redirects, and avoid having to push to the gh-pages branch which is problematic.

- [x] verify that netlify does not impose any cookies.
- [x] verify that netlify will maintain https certs for custom domains on non-netlify nameservers 
- [x] figure out how to transition DNS from gh-pages to netlify with minimal downtime

i have verified that the following steps would work - the process is simple, but it _will_ result in some amount of downtime - so performing it after hours would be better.

- change DNS CNAMEs for both `projectriff.io` and `www.projectriff.io` to point to `projectriff.netlify.com`
- in Netlify site settings, add custom domain for `projectriff.io` - this will auto-add `www.projectriff.io`.
- Netlify will immediately try to auto-provision the letsencrypt cert and this will succeed once the DNS pointers to netlify.com are in place (and the old github.io CNAMEs are no long er being served from cache)

[netlify docs](https://www.netlify.com/docs/ssl/) 
The alternative, to avoid zero downtime, would be to self-provision our own certs for the custom domain on netlify, and then, after transitioning DNS, switch to their letsencrypt automation. I have not tested this approach.

**Comment by scothis** [comment]
@jldec is this still worth doing?

**Comment by jldec** [comment]
no need with the github action for publishing to gh-pages in place :)
https://github.com/projectriff/projectriff.io/blob/master/.github/workflows/publish.yaml
