### ISSUE TITLE
Older blog posts are hard to navigate

### ISSUE THREAD

**Issue by jldec** [projectriff/projectriff.io#156]
We're no longer showing next-post and previous-post nav buttons and the list on the left doesn't include older posts, so it's actually very hard to navigate between older blog posts

e.g. https://projectriff.io/blog/2017/12/07/springone-platform-keynote-2017

i would suggest either showing the whole list of posts on the left or adding next/prev navigation.

**Comment by scothis** [comment]
https://projectriff.io/blog/ has prev/next links to paginate through the full listing.

**Comment by jldec** [comment]
those scroll through next/prev listing-page of 10 posts - it's possible to use that, but not good UX.

the problem is that once you're on the actual post (e.g. if you were linked there) you can't easily get to the listing page to figure out the next post, and you can't see the next post in the sidebar.

**Comment by scothis** [comment]
Docusaurus doesn't support prev/next links for individual blog posts like it does for docs.

**Comment by jldec** [comment]
How about putting back the full list in the navbar on the left.

**Comment by scothis** [comment]
> How about putting back the full list in the navbar on the left.

I think that's an even worse UX that doesn't scale. The current set of 'recent posts' go back a year, how much further back in time do you think people actually want to read?

**Comment by jldec** [comment]
closing
