### ISSUE TITLE
Include uninstall instructions for the previous version

### ISSUE THREAD

**Issue by trisberg** [projectriff/projectriff.io#171]
Should we include uninstall instructions for the previous version, seems a bit heavy handed to have to delete the environment and recreate it. There are some notes here: https://github.com/projectriff/charts/tree/v0.4.0#uninstall

**Comment by ekcasey** [comment]
If we do this I think we should include uninstall instructions for `v0.5.0` as well, for the same reasons.

**Comment by trisberg** [comment]
I'm not against including uninstall instructions for v0.5.0, although with `kapp` we should now be able to upgrade from one minor version to the next
