### ISSUE TITLE
Improve v0.5 streaming getting started 

### ISSUE THREAD

**Issue by jldec** [projectriff/projectriff.io#194]
Users trying out streaming with v0.5 should be able to install, create a streaming function, deploy it as a streaming processor, and observe the results of processing streams.

The last step is currently missing in https://projectriff.io/docs/v0.5/runtimes/streaming

One solution would be to deploy [dev-utils](https://github.com/projectriff/dev-utils) to "watch" the input and output streams.

**Comment by trisberg** [comment]
not sure how easy it would be to "watch" the output since we removed the `--payload-as-string` option, all you would see is the encoded value. Seems to require jumping through hoops with jq+xargs+base64  to see the actual text
