### ISSUE TITLE
Consistent use of INGRESS and also case for headings

### ISSUE THREAD

**Issue by trisberg** [projectriff/projectriff.io#213]
In PR #212 we changed the INGRESS lookup for v0.5 docs, we should port these changes to v0.6 docs as well.

We are using variety of env vars for INGRESS / INGRESS_PORT in 0.5 and 0.6 docs. We should make the use of them consistent throughout getting-started and runtime docs.

Also some change for case in headings were made in #212 and we should make all docs use the same case for `###` level headings.

**Comment by scothis** [comment]
@jldec are you planning to work this issue?

**Comment by jldec** [comment]
Would prefer if this was reassigned - thanks @scothis
