### ISSUE TITLE
riff create node should include a namespace

### ISSUE THREAD

**Issue by bmullan-code** [projectriff/projectriff.io#34]
In file _docs/010-getting-started-on-minikube.md 
the riff create node command fails as it assumes namespace 'test' exists. 

`
riff create node --name square --input numbers --filepath .
`

the following works. 
`
riff create node --namespace default --name square --input numbers --filepath .
`

**Comment by trisberg** [comment]
the CLI uses `default` unless you change it, so those two commands should both work - could you post the errors you see from the first one?

**Comment by bmullan-code** [comment]
Here's what I got without having a 'test' namespace. 

riff create node --name square --input numbers --filepath .
Skipping existing file /Users/bmullan/Downloads/riffjs/square-topics.yaml  - set --force to overwrite.
Skipping existing file /Users/bmullan/Downloads/riffjs/square-function.yaml  - set --force to overwrite.
Skipping existing file /Users/bmullan/Downloads/riffjs/Dockerfile  - set --force to overwrite.
Skipping existing file /Users/bmullan/Downloads/riffjs/.dockerignore  - set --force to overwrite.
Building image ...
[STDOUT] Sending build context to Docker daemon  8.192kB
[STDOUT] Step 1/3 : FROM projectriff/node-function-invoker:0.0.8
[STDOUT]  ---> 6b42d1262422
[STDOUT] Step 2/3 : ENV FUNCTION_URI /functions/square.js
[STDOUT]  ---> Using cache
[STDOUT]  ---> 553558d0375b
[STDOUT] Step 3/3 : ADD square.js ${FUNCTION_URI}
[STDOUT]  ---> Using cache
[STDOUT]  ---> b84129d09960
[STDOUT] Successfully built b84129d09960
[STDOUT] Successfully tagged myaccount/square:0.0.1
Applying resources in .

Error from server (NotFound): error when creating "/Users/bmullan/Downloads/riffjs/riffjs-function.yaml": namespaces "test" not found
Error from server (NotFound): error when creating "/Users/bmullan/Downloads/riffjs/square-function.yaml": namespaces "test" not found
Error from server (NotFound): error when creating "/Users/bmullan/Downloads/riffjs/riffjs-topics.yaml": namespaces "test" not found
Error from server (NotFound): error when creating "/Users/bmullan/Downloads/riffjs/square-topics.yaml": namespaces "test" not found


I had just installed minikube. After seeing the error I created a namespace 'test' and it worked.

**Comment by trisberg** [comment]
does your kubectl config specify a namespace? `kubectl config get-contexts` has a NAMESPACE column

do you have an env var `RIFF_NAMESPACE=test` set or do you have a `$HOME/.riff.yaml` file that specifies namespace? See https://github.com/projectriff/riff/tree/master/riff-cli#riff-cli-configuration

**Comment by jldec** [comment]
per https://github.com/projectriff/riff/pull/364 which fixed https://github.com/projectriff/riff/issues/345
we should be respecting your kubectl context default namespace even if it is not "default"

**Comment by bmullan-code** [comment]
@trisberg thanks! my bad, I had a namespace in the .yaml file. Appreciate the help.
