### ISSUE TITLE
Add docs for installing on PKS

### ISSUE THREAD

**Issue by trisberg** [projectriff/projectriff.io#54]
See: https://content.pivotal.io/blog/why-serverless-matters-to-your-enterprise-a-look-at-common-use-cases-plus-a-quick-tutorial-with-riff-and-kubernetes

**Comment by glyn** [comment]
What, if anything, remains to be done now that https://github.com/pivotal-cf/docs-pfs/pull/11 is merged? /cc @georgeharley

**Comment by jldec** [comment]
not required for riff v0.2.0 milestone.

**Comment by glyn** [comment]
The title of this issue is misleading if the issue is actually about linking to the blog in the first comment.

**Comment by scothis** [comment]
PKS is not a supported environment for riff
