### ISSUE TITLE
add docs for each language invoker

### ISSUE THREAD

**Issue by jldec** [projectriff/projectriff.io#6]
It's too hard for users to find docs about writing riff functions in each supported language.

How about incorporating README content e.g. from the
[node invoker](https://github.com/projectriff/node-function-invoker/blob/master/README.md) and other invoker repos?

**Comment by trisberg** [comment]
Looks like we are copying the READMEs by hand right now, any plans on automating this?

**Comment by scothis** [comment]
done https://projectriff.io/docs/v0.4/invokers/java
